on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gnupg \
            libudev-dev \
            libsasl2-dev \
            libssl-dev \
            libzstd-dev
          sudo apt-get satisfy -f -y "protobuf-compiler (>=3.15)"

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: cargo build
        run: cargo build --workspace

      - name: cargo test
        run: cargo test --workspace -- --test-threads=16
